let sqlStrings =  {
    createTable: {
        createTableItems: 'CREATE TABLE IF NOT EXISTS table_items (`IID` INT NOT NULL,`Name` VARCHAR(255) NOT NULL,PRIMARY KEY (`IID`))',
        createTablesArmbands: 'CREATE TABLE IF NOT EXISTS `table_armbands` (`AbID` INT NOT NULL,`IID` INT NOT NULL,`image` VARCHAR(32) NOT NULL,`name` VARCHAR(255) NOT NULL,`color` VARCHAR(255) NOT NULL, PRIMARY KEY (`AbID`), FOREIGN KEY (`IID`) REFERENCES `table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
        createTableBackpacks: 'CREATE TABLE IF NOT EXISTS `table_backpacks` (`BID` INT NOT NULL, `IID` INT NOT NULL, `name` VARCHAR(255) NOT NULL, `image` VARCHAR(32) NOT NULL, `inner_grid` VARCHAR(255) NOT NULL, `outer_grid` VARCHAR(255) NOT NULL, `slots` INT NOT NULL, `storage_efficiency` DECIMAL(30,2) NOT NULL, `weight` DECIMAL(30,1) NOT NULL, PRIMARY KEY (`BID`), FOREIGN KEY (`IID`) REFERENCES table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
        createTableEyewears: 'CREATE TABLE IF NOT EXISTS `table_eyewears` (`EwID` INT NOT NULL AUTO_INCREMENT, `IID` INT NOT NULL, `image` VARCHAR(32) NOT NULL, `name` VARCHAR(255) NOT NULL, PRIMARY KEY (`EwID`), FOREIGN KEY (`IID`) REFERENCES `table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
        createTableHeadset: 'CREATE TABLE IF NOT EXISTS `table_headsets` (`HID` INT NOT NULL AUTO_INCREMENT, `IID` INT NOT NULL, `image` VARCHAR(32) NOT NULL, `name` VARCHAR(255) NOT NULL, PRIMARY KEY (`HID`), FOREIGN KEY (`IID`) REFERENCES table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
        createTableSecureContainers: 'CREATE TABLE IF NOT EXISTS `table_secure_containers` (`ScID` INT NOT NULL AUTO_INCREMENT, `IID` INT NOT NULL, `image` VARCHAR(32) NOT NULL, `name` VARCHAR(255) NOT NULL, `inner_grid` VARCHAR(255) NOT NULL, `total_slots` INT NOT NULL, PRIMARY KEY (`ScID`), FOREIGN KEY (`IID`) REFERENCES `table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
        createTableContainers: 'CREATE TABLE IF NOT EXISTS `table_containers` ( `CoID` INT NOT NULL, `IID` INT NOT NULL, `image` VARCHAR(32) NOT NULL, `name` VARCHAR(255) NOT NULL, `inner_dimensions` VARCHAR(255) NOT NULL, `outer_dimensions` VARCHAR(255) NOT NULL, `efficiency` DECIMAL(30,2) NOT NULL, `total_slots` INT NOT NULL, PRIMARY KEY (`CoID`), FOREIGN KEY (`IID`) REFERENCES table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
        createTableProvisions: 'CREATE TABLE IF NOT EXISTS `table_provisions` (`PID` INT NOT NULL, `IID` INT NOT NULL, `image` VARCHAR(32) NOT NULL, `name` VARCHAR(255) NOT NULL, `energy` INT NOT NULL, `hydration` INT NOT NULL, PRIMARY KEY (`PID`), FOREIGN KEY (`IID`) REFERENCES table_items` (`IID`) ON DELETE NO ACTION ON UPDATE NO ACTION)',
    }
}

export default sqlStrings;